### ISSUE TITLE
Hardcoded value for Zero Payment provider alias

### ISSUE THREAD

**Issue by bjarnef** [vendrhub/vendr-checkout#10]
I noticed there is a constant for the Zero Payment provider alias here, which is used in most of the code:
https://github.com/vendrhub/vendr-checkout/blob/eb72cd71da645a5e2e735e86816e29fcebb832ed/src/Vendr.Checkout/VendrCheckoutConstants.cs#L38

However here it is hardcoded to `zeroValue`:
https://github.com/vendrhub/vendr-checkout/blob/b3a7e6c5293b1411f6e061922d138ff28bc49c08/src/Vendr.Checkout/Web/UI/App_Plugins/VendrCheckout/Views/VendrCheckoutMaster.cshtml#L113

**Comment by mattbrailsford** [comment]
There is a slight difference here. One is the payment method alias, where the other is the payment provider alias. In the later file it is excluding all payment methods that use the zero value provider in case there’s more than one.

**Comment by bjarnef** [comment]
Ahh yes of course. I was a bit too fast to report that issue.
However doesn't Vendr core has a constant for the Zero Value payment provider alias to use here?

**Comment by mattbrailsford** [comment]
Update on this, we didn't have constants for these in Vendr core but I've added them now for v2.1.1 however because we are targeting Vendr 2.0.0 atm and don't want to have to force the upgrade we'll have to stick with the magic string in this package for the time being at least.
