### ISSUE TITLE
Non-existent discount codes should throw validation error

### ISSUE THREAD

**Issue by chrisdent14** [vendrhub/vendr-checkout#11]
I am using:
Umbraco 8.6.4
Vendr 1.3.2
Vendr.Checkout .1.1.7

There is no validation message output on the Views/Partials/VendrCheckoutInformationPage.cshtml view to show a message for an invalid discount code.

I took a look at the Vendr demo store repo and the validation message output is there:
https://github.com/vendrhub/vendr-demo-store/blob/8a725eb450a442fa79ac3f8caf83e253e66bf01a/src/Vendr.DemoStore.Web/Views/CheckoutInformationPage.cshtml#L15

However, from looking at the code for the 'ApplyDiscountOrGiftCardCode' method on both the Vendr.Checkout and Vendr Demo Store repos (links below), there is no key set when the Model Error is set meaning this error cannot be accessed to be displayed.

Vendr.Checkout VendrCheckoutSurfaceController.cs (line 44)
https://github.com/vendrhub/vendr-checkout/blob/d9db411ae921ea4c1c3d055b06f267ff9b3e0bcf/src/Vendr.Checkout/Web/Controllers/VendrCheckoutSurfaceController.cs#L44

CheckoutSurfaceController.cs (line 45)
https://github.com/vendrhub/vendr-demo-store/blob/8a725eb450a442fa79ac3f8caf83e253e66bf01a/src/Vendr.DemoStore/Web/Controllers/CheckoutSurfaceController.cs#L45

I also brought down the Vendr.Checkout repo to debug this locally and found that the ValidationException catch is actually never entered, even if the discount code does not exist, so the AddModelError lines, as stated above, would never be hit.

Hopefully this is enough information to go on but please let me know if there is anything else you need to help you investigate

Cheers
Chris

**Comment by mattbrailsford** [comment]
@chrisdent14 hmmm

So Vendr doesn't error if the discount code doesn't apply any discount. Instead it just says "so these are the codes you've applied" but this doesn't mean a discount is applied. To know that, you'd need to read the "IsFulfilled" property of the discount code object on the order. The main reason for this is that discounts aren't known until the order is calculated, so we need to allow codes to be added such that they can be calculated when later when the order is calculated.

Only thing I could think to do is maybe have some API option or something that says "Remove unfulfilled discount codes" 🤔

**Comment by chrisdent14** [comment]
@mattbrailsford Cheers for the quick reply.

Okay, so what would constitute a ValidationException when applying a discount code?

**Comment by mattbrailsford** [comment]
It would only currently throw a validation exception if the code isn't Valid (the associated Discount is inactive, or not within it's date range).

**Comment by chrisdent14** [comment]
@mattbrailsford Okay that's fine. I think I can work with that information for now.

I have read my original description back and have realised I missed something crucial. This is for a discount code that **does not exist** in the system at all. Do you think this should throw a validation exception as the code entered is not in the system?

It makes sense to me the logic you described for a discount code that does exist, has been applied to the order as the discount will be worked out later in the process

**Comment by mattbrailsford** [comment]
Hmmm, yea, that probably should be like you say. If there is no discount at all with that code, it should fail validation.

I'll make that the focus of this issue and take a deeper look 👍

**Comment by chrisdent14** [comment]
@mattbrailsford Perfect, thanks. Do you me to add an edit to my original description?

**Comment by mattbrailsford** [comment]
@chrisdent14 I've just updated the title, but the body can stay. I'll see if I can get it into this 1.3.4 patch release for the end of the week. Shouldn't be too hard if it's just another validation rule 👍

**Comment by chrisdent14** [comment]
@mattbrailsford Just to add to this, should line 44 of the 'ApplyDiscountOrGiftCardCode' method also be amended to include the key name of 'code' to allow the validation message to be displayed?

https://github.com/vendrhub/vendr-checkout/blob/d9db411ae921ea4c1c3d055b06f267ff9b3e0bcf/src/Vendr.Checkout/Web/Controllers/VendrCheckoutSurfaceController.cs#L44

**Comment by mattbrailsford** [comment]
I'll double check this too. No key name should just make it global error which I think we still have the ability to display. Key names are only useful if you are looking to do inline validation, we we don't in Vendr Checkout.

**Comment by mattbrailsford** [comment]
Actually, the validation rule logic is Vendr project specific, so I may just transfer this issue to the Vendr issue tracker instead.

**Comment by chrisdent14** [comment]
> I'll double check this too. No key name should just make it global error which I think we still have the ability to display. Key names are only useful if you are looking to do inline validation, we we don't in Vendr Checkout.

Yeah, I mentioned it again because the Vendr Demo store is checking for the key 'code' on the Information page so wondered if this is what it should have been set to?

https://github.com/vendrhub/vendr-demo-store/blob/8a725eb450a442fa79ac3f8caf83e253e66bf01a/src/Vendr.DemoStore.Web/Views/CheckoutInformationPage.cshtml#L15

**Comment by mattbrailsford** [comment]
Ahh, ok, good point. I'll leave it here for now and raise another issue on Vendr core repo if I think it warrants it. 👍
