### ISSUE TITLE
Use Cookies

### ISSUE THREAD

**Issue by JamieTownsend84** [vendrhub/vendr-checkout#17]
If the 'Use Cookies' property is set to false the Vendr checkout Addon does not work. Not sure if this is expected behaviour or not but spent a long time debugging to figure this out, so if expected could we add some docs to explain this prereq.

The issue is the method 'RedirectEmptyCart' - this always returns an empty current cart so will just redirect to the backup page configured.

**Comment by mattbrailsford** [comment]
It is not expected no. If cookies are disabled it should resort to storing session data in the .NET session object. 

Will have to review why that may not be happening.

**Comment by mattbrailsford** [comment]
@JamieTownsend84 ok, so it looks like we might need an alternative approach to redirecting if the cart is empty.

We currently use a `PublishedRequest.Prepared` to hijack any request for any checkout step page and if the order is null, we redirect to the cart page. The problem appears to be that the `PublishedRequest.Prepared` event is fired from with the `UmbracoModule` which is a `IHttpHandler` used to handle Umbraco's routing. Unfortunately it appears that the Session object isn't available in a `IHttpHandler` unless that handler implementation also implements the `IRequiresSessionState` interface, which the `UmbracoModule` does not.

Ultimately this means that the session is not going to be available from within this event handler and so it looks like we may need an alternative solution.

Best I can think of at the moment is that we look to use a hijacking base controller class for the checkout steps and perform the redirect logic in there as hopefully it should have a session available at that point, though I'll need to test it.

**Comment by mattbrailsford** [comment]
@JamieTownsend84 how did you install the package? If it's via NuGet, I've just pushed a fix to our unstable feed https://nuget.outfield.digital/unstable/vendr/v3/index.json which you can register in Visual Studio as a custom NuGet feed source. You'd want the Vendr.Checkout.1.2.1-beta0005 package. If you want to try upgrading to this, it should fix your problem.

I've ultimately moved the empty cart check out the event handler and into the hijack controllers we already have in place and that seems to work.

If you used the Umbraco package,  here is a link to the unstable build 

[Vendr.Checkout.1.2.1-beta0005.zip](https://github.com/vendrhub/vendr-checkout/files/6492925/Vendr.Checkout.1.2.1-beta0005.zip)

Matt

**Comment by JamieTownsend84** [comment]
Thanks @mattbrailsford 

I installed it via nuget so updated to: Vendr.Checkout.1.2.1-beta0005 and this resolves the problem.
