### ISSUE TITLE
Original amount is passed to payment provider after Gift Card is used

### ISSUE THREAD

**Issue by prjseal** [vendrhub/vendr-checkout#19]
**Describe the bug**
When using a gift card for the full price of the item, you are still taken to the payment page and chosen payment method wants to take the full amount.

**Steps To Reproduce**
1. Create a discount code for the value of an item in the store
2. Add the item to the basket
3. Go to checkout
4. Add gift card code
5. Price is updated in the summary
6. Continue to payment screen
7. Still wants to take the full payment

**Expected behavior**
The amount owed should be adjusted based on the gift card value, and if the amount owed is 0 then no payment method should be needed and no payment should be taken.

**Screenshots**

**Additional context**
I am using Vendr with Vendr Checkout

**Vendr version:**
Vendr version 1.8.3
Vendr.Checkout version 1.2.0

**Comment by mattbrailsford** [comment]
I've moved this issue to the Vendr Checkout repo as I believe it's potentially a bug there.

Ultimately I think the payment method selection page needs updating, and specifically line 33

https://github.com/vendrhub/vendr-checkout/blob/dev/src/Vendr.Checkout/Web/UI/App_Plugins/VendrCheckout/Views/VendrCheckoutPaymentMethodPage.cshtml#L33

It is currently checking the total price to see if it is zero, but gift cards are applied to the transaction amount, so that page should probably be checking the order.TransactionAmount instead.

May be worth swapping that by hand and just see if it resolves the issue. If so, then I can update the package accordingly.

**Comment by prjseal** [comment]
Thanks Matt. I was able to get this working by creating a Zero value payment provider and changing TotalPrice to TransactionAmount on that line you provided. 

I also needed to change the alias for the zero value payment provider check to be "zeroValue". https://github.com/vendrhub/vendr-checkout/blob/d17118758991c7eb7130dbc6a1e5557129100e9c/src/Vendr.Checkout/Web/UI/App_Plugins/VendrCheckout/Views/VendrCheckoutPaymentMethodPage.cshtml#L22

But that might be because I upgraded from an older version of Vendr Checkout. The alias in the constant might be correct for new sites. I don't know.

Thanks for looking into it so soon though.

**Comment by prjseal** [comment]
@mattbrailsford this issue is still not resolved. While the fix you described worked when there is a zero balance left to pay, it doesn't work when there is a positive balance left to pay. It still tries to take the full amount.

**Comment by mattbrailsford** [comment]
Which payment method are you using?

**Comment by prjseal** [comment]
Square and PayPal

**Comment by mattbrailsford** [comment]
And both are attempting to capture the whole value? and not the value excluding the gift card amount?

**Comment by prjseal** [comment]
Yes

**Comment by mattbrailsford** [comment]
Which versions of the providers?

**Comment by prjseal** [comment]
PayPal 1.0.2
Square 1.0.0

**Comment by prjseal** [comment]
@mattbrailsford looks like i need to update to the latest paypal provider and we need to update the square one to use the transaction amount which you introduced in vendr 1.4

**Comment by mattbrailsford** [comment]
Sorry, forgot to reply, but yea, that's what I was thinking.

**Comment by prjseal** [comment]
I've just created an Issue for the square one https://github.com/vendrcontrib/vendr-payment-provider-square/issues/3
