### ISSUE TITLE
Using wrong price to determine if order is zero value

### ISSUE THREAD

**Issue by royberris** [vendrhub/vendr-checkout#25]
`Mollie.Api.Client.MollieApiException: Unprocessable Entity - The amount is lower than the minimum`

When we have a gift card and I apply that to a order. The total amount is `0`. I would expect Vendr to skip the Mollie step now. Instead it will throw a exception on the MollieApi. 

If expected behaviour is what should happen. What would happen to the transaction ID which is usually provided by Mollie?

**Comment by mattbrailsford** [comment]
Ahh, good spot @royberris it looks like we may be looking at the wrong price. This should be the `currentOrder.TransactionAmount.Value` that should be checked for zero value.

I've moved this issue to the Vendr Checkout repo as this is more an issue with that than with the Mollie provider.

**Comment by mattbrailsford** [comment]
Closing this issue as the current version does now check the `TransactionAmount`
