### ISSUE TITLE
Feature Request: Allow checkout templates to be moved to main Views

### ISSUE THREAD

**Issue by craigs100** [vendrhub/vendr-checkout#40]
To allow modification of the checkout pages, it would be good to be able to move the relevant templates to the project's Views folder so they're not overwritten on restarts.  Maybe add an optional Templates path to the checkout page like has been done for email templates in the main product.

For instance, there's currently no info on what happens with the marketingOptIn checkbox in the Customer Information page. My client wants it removed, but it can't be done.  It's not even possible to hide it with css.  

There's a checkbox for agreeing to terms and conditions, but no way of adding a link to them. 

There's no way of correcting the link back to the store, it's set at "/" which isn't necessarily the "store" in a large site.

et al.

**Comment by mattbrailsford** [comment]
This is already possible, you can set a `VendrCheckout:RootViewPath` app setting to point to another location and copy the views from the `App_Plugin` folder into it. Vendr Checkout will then look for the views there.

Alternatively you can also setup your own templates in the back office and assign them to the Vendr Checkout doc types. If the doc type has a template defined it will use that or fallback to the looking in the `VendrCheckout:RootViewPath` location.

**Comment by craigs100** [comment]
It may be possible, but not if you don't know about it. I've just looked through the Repo info and the Vendr Checkout docs and find no reference to it. Searching the code for what you just told me I find a reference at [‎src/Vendr.Checkout/Configuration/VendrCheckoutSettings.cs](https://github.com/vendrhub/vendr-checkout/blob/b9922ca5e02e45352aa87be3448643da0d99d8b0/src/Vendr.Checkout/Configuration/VendrCheckoutSettings.cs#L18) So from that I guess it's to be placed in the root of the appsettings.json. 

It would have been really helpful if it had been in the docs ;)

Thanks.
