### ISSUE TITLE
YSOD while accessing an empty cart

### ISSUE THREAD

**Issue by thomas-jf** [vendrhub/vendr-checkout#6]
Hi,
I'm getting YSOD with a message "Object reference not set to an instance of an object" in App_Plugins\VendrCheckout\Views\VendrCheckoutInformationPage.cshtml Line: 42

<img width="761" alt="vendrysod" src="https://user-images.githubusercontent.com/6547650/86720738-9ab38280-c025-11ea-8de7-b378b0f1aae4.png">

I would rather expect a message "Your cart is empty" or redirect back to the cart (Matt's sugestion on Vendr support)

Regards
Tomasz

**Comment by mattbrailsford** [comment]
Thanks @thomas-jf 

I've just pushed a potential fix in commit 7b1c329892315d823f9962a8b53854fec0f4556b although I haven't tested it yet. Your welcome to give the unstable build a try which you can access on our unstable nuget feed at https://nuget.outfield.digital/unstable/vendr/v3/index.json. You'll want the Vendr.Checkout 1.1.5-beta0006 build. Given it's just a background code change, just installing the package should be enough. You don't have to run the installer again.

I'll try and take a look at testing it myself a little later

/Matt

**Comment by thomas-jf** [comment]
Hi @mattbrailsford 

I have just tested 1.1.5-beta0006 build and it looks like it is working better now. I'm redirected to the Checkout Back Page.

/Tomasz

**Comment by mattbrailsford** [comment]
Awesome! Thanks for test @thomas-jf 👍

I'll try and get an official release out this week / early next.

**Comment by mattbrailsford** [comment]
Oops, forgot to say, this fix got rolled out last week. Thanks again for reporting 👍
