### ISSUE TITLE
Payment method not allowed in current country but listed on checkout page

### ISSUE THREAD

**Issue by thomas-jf** [vendrhub/vendr-checkout#7]
Hi,
I don't know if that is a bug or jus a misconfiguration.
I have three payment methods:

![billede](https://user-images.githubusercontent.com/6547650/87761182-50928400-c811-11ea-92d1-8ecfab405734.png)

but Invoicing is not allowed in any countries:

![billede](https://user-images.githubusercontent.com/6547650/87761234-67d17180-c811-11ea-8001-68e6aa79222c.png)

but is listed on the Payment methods checkout page:

![billede](https://user-images.githubusercontent.com/6547650/87761352-97807980-c811-11ea-852f-462a16c75dda.png)

"Fortunately" it gives an error, when one tries to use it and falls back to the default pm (Bambora):

![billede](https://user-images.githubusercontent.com/6547650/87761398-aff09400-c811-11ea-82ec-d8a041abdf36.png)

Regards
Tomasz

**Comment by mattbrailsford** [comment]
Thanks @thomas-jf that does indeed sound like a bug. I think we must not be filtering the methods that aren’t allowed. We can definitely sort that 👍🏻

**Comment by thomas-jf** [comment]
It isn't something critical to me just right now and I'm sure that I could fix it by my self, but I don't have time right now and I need to do a custom check out flow to the project anyway. (And as a third excuse, I haven't done a pull request to the open source project yet. So it will be the very first time :) )

But I think that Vendr and Vendr.Checkout are awesome and we sure will use them in other projects (we used TC very often).

/Tomasz

**Comment by mattbrailsford** [comment]
Hey, just spending the time to submit an issue with fully documented replication steps is a great contribution in itself so I appreciate you trying it and taking the time to report it 🙏

**Comment by mattbrailsford** [comment]
Should be fixed in commit d8088116bd66a24e6d12f9126af7bdb7e97855bd will be in an upcoming 1.1.6 release 👍
